# Generated by Django 2.2.13 on 2020-11-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201120_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund',
            new_name='refund_requested',
        ),
    ]
