# Generated by Django 2.1.7 on 2020-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_category', models.CharField(choices=[('A', 'About_us'), ('N', 'News'), ('E', 'Events'), ('S', 'Sitemap')], max_length=2)),
                ('article_slug', models.SlugField()),
                ('article_description', models.TextField()),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
