# Generated by Django 2.1.7 on 2020-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201206_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_category',
            field=models.CharField(choices=[('A', 'About_us'), ('N', 'News'), ('E', 'Events'), ('C', 'Contact'), ('S', 'Sitemap')], max_length=2),
        ),
    ]
