# Generated by Django 2.1.7 on 2020-12-06 06:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_description',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_body',
           
            field=models.CharField( max_length=202),
        ),
    ]
