# Generated by Django 2.1.7 on 2020-12-06 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_description',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_body',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
