# Generated by Django 2.1.7 on 2020-12-06 10:16

# import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
#             field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
            field = models.CharField(max_length=150),
        ),
    ]
