# Generated by Django 2.1.7 on 2020-12-06 14:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201206_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
    ]
