# Generated by Django 2.1.7 on 2020-12-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201207_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'FASTENERS'), ('S', 'SIGNS'), ('C', 'CUTTING'), ('D', 'DRILLING'), ('A', 'ADHESIVE'), ('T', 'TOOLS')], max_length=2),
        ),
    ]
